server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/ninadam/config-server/
          skipSslValidation: true
          searchPaths: config, userservice
          username: ninadam
          password: luzanimetropola10

