server:
  port: 8080
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/ninadam/config-server/
          skipSslValidation: true
          searchPaths: userservice
          username: ninadam
          password: luzanimetropola10

#server:
#   port: 8080
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file:///C:/Users/Nina/Desktop/Lokavor/Demo/config-server/src/main/resources/config/userservice

##
