server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/ninadam/config-repo/
          searchPaths: user
          username: ninadam
          password: luzanimetropola10

