spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/lokavor_dev"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.type: "org.postgresql.ds.PGSimpleDataSource"